export const LIMITS = {
	MAX_SERIES_PER_AUTHOR: 10,
	MAX_BOOKS_PER_SERIE: 20,
	MAX_CHARACTERS_PER_SERIE: 500,
	MAX_CHAPTERS_PER_BOOK: 100,
	MAX_PLACES_PER_SERIE: 250,
};

export const DEPTHS = {
	COMMENT_DEPTH: 5,
	PLACE_DEPTH: 5,
};
